#Name of the workflow 
name: CiCd
#This triggers only if manually run the pipeline
# on:
#   workflow_dispatch: 

#Triggerring action when particular .html file get updated in main branch
# on:
#   push:
#     branches: main
#     paths: '**.html'

#This lets u to select the option among the list of choices
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: This is the environment value where this workflow runs
        default: 'clone'
        required: true
        type: choice
        options:
          - clone
          - test
          - deploy
    
jobs:    
  clone:
    needs: [deploy,run]
    runs-on: ubuntu-slim
    steps:
      - name: code clonning
        run: echo "Clonning the code from github"
  test:
    needs: clone
    runs-on: ubuntu-slim
    steps:
      - name: testing the code
        run: echo "Testing the code clonned from the Github"
  run:
    needs: deploy
    runs-on: ubuntu-slim
    steps:
      - name: run the app
        run: echo "Running the app"
  deploy:
    runs-on: ubuntu-slim
    steps:
      - name: deploying the app 
        run: echo "Deploying the app in docker container"
