#name of the workflow
name: hello-workflow
#on when it should trigger
on:
  push:
    branches: [master]
#jobs inside the workflow
jobs:
  #name of the first job: greet
  greet:
      #where it should run eg: ubunut machine.
      runs-on: ubuntu-latest
      #what are the steps to execute 
      steps:
        - name: say hello user
          run: echo "Hello Nithin"
        - name: get the username
          run: echo "I am $USER"
