#name of the workflow
name: hello-workflow
#on when it should trigger [ This is the automatic workflow and called "deployment" ] 
on:
  push:
    branches: [main]
#jobs inside the workflow
jobs:
  #name of the first job: greet
  greet:
      #where it should run eg: ubunut machine.
      runs-on: ubuntu-latest
      #what are the steps to execute 
      steps:
        - name: say hello user
          run: echo "Hello Nithin"
        - name: get the username
          run: echo "I am $USER"
  details:
      runs-on: ubuntu-slim
      steps:
        - name: python and docker versions
          run: docker --version && python --version
        - name: getting path
          run: which docker && which python
